title = "Christopher Swayne"
baseURL = "https://c-swa.github.io/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/christopher.swayne.98"
  twitter = ""
  instagram = "https://www.instagram.com/c-swa"
  youtube = "https://www.youtube.com/channel/UCwZxGSx84DwkOVscTxJC2OA?"
  github = "https://www.github.com/c-swa"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/home-image.jpg"
  recent_posts_number = 2
